{{
config
(
    materialized = "incremental",
    incremental_strategy = "merge",
    unique_key = "PRODUCT_ID",
    merge_exclude_columns = ["INSERT_DTS"],
    schema = "TRANSFORMED"
)
}}

WITH product_raw AS
(
    SELECT 
    SOURCE_DATA:product_id AS PRODUCT_ID,
    SOURCE_DATA:product_name AS PRODUCT_NAME,
    SOURCE_DATA:category AS PRODUCT_CATEGORY,
    SOURCE_DATA:unit_price AS PRODUCT_PRICE,
    SOURCE_DATA:quantity AS PRODUCT_STOCK_QUANTITY,
    SOURCE_DATA:supplier_name AS PRODUCT_SUPPLIER_NAME,
    CURRENT_TIMESTAMP(6) AS INSERT_DTS,
    CURRENT_TIMESTAMP(6) AS UPDATE_DTS
    FROM {{ ref('product_raw') }}

    {% if is_incremental() %}
    WHERE INSERT_DTS > (SELECT MAX(INSERT_DTS) FROM {{this}})
    {% endif %}
)

SELECT
CAST(PRODUCT_ID AS INT) AS PRODUCT_ID,
CAST(UPPER(PRODUCT_NAME) AS STRING) AS PRODUCT_NAME,
CAST(UPPER(PRODUCT_CATEGORY) AS STRING) AS PRODUCT_CATEGORY,
CAST(PRODUCT_PRICE AS FLOAT) AS PRODUCT_PRICE,
CAST(PRODUCT_STOCK_QUANTITY AS INT) AS PRODUCT_STOCK_QUANTITY,
CAST(UPPER(PRODUCT_SUPPLIER_NAME) AS STRING) AS PRODUCT_SUPPLIER_NAME,
CAST(INSERT_DTS AS TIMESTAMP(6)) AS INSERT_DTS,
CAST(UPDATE_DTS AS TIMESTAMP(6)) AS UPDATE_DTS
FROM product_raw