version: 2

models:
    - name: product_raw
      description: "dbt model to create the product raw table"
 
    - name: product_transformed
      description: "dbt model to create the product transformed table"

 

sources:
    - name: product
      database: DEA_BATCH_SCD2
      schema: RAW
      tables:
        - name: PRODUCT_CP